language: java
jdk: oraclejdk7
env:
    matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
    - tar xzf android-sdk_r23.0.2-linux.tgz
    - wget https://dl-ssl.google.com/android/repository/build-tools_r21.1.1-linux.zip
    - unzip build-tools_r21.1.1-linux.zip -d $ANDROID_HOME
    - mkdir -p $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/android-5.0 $ANDROID_HOME/build-tools/21.1.1
    - echo yes | android update sdk --filter platform-tools,build-tools-20,android-21,extra-android-support --no-ui --force
script:
    - ./gradlew build
    - ./gradlew dist
