language: java
jdk: oraclejdk7
env:
    global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=builds.catacombsnatch.net"
    - secure: "klyzaKQjpBXjR/1RLD9iCFA6f7KL2zUfxzmQRrlrkksMt7hMyzC8PALkxs4u\nfGXUv0+Eq6cTacHHR0szhMb9hTJA8678qLmZxbAlHlqaSs++WpGaU59y5Ap2\n0e7C42JWgtO/p8CNt5NdznnISdYUWI4UyIoDnmyF2oCaNEP1SVs="
    - secure: "KrVr7iCqHp+DRPT6OP5f4QFYPRprEGJ2sbbz7IPh637TwH7YuOQqWBgATfja\nEAiNq08Q3rc5TSqOHLSrApx7wcfu4BjBe3xcRPwc7qdZm0xYjmhcT0rGhjkR\ni20x/etaRXDNnnlA/2JX9VRK+zxQf9rrSkAuCmW+WNBf1NXH6x8="

before_script:
    - "gem install travis-artifacts"
after_test:
    - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
